### ISSUE TITLE
Support external storage 

### ISSUE THREAD

**Issue by gythialy** [qlcchain/go-qlc#43]
- [ ] Define storage interface
- [ ] implement storage interface base on [Redis](https://redis.io/)
- [ ] implement storage interface base on [IPFS](https://ipfs.io/)
- [ ] other implementation for Montnets

**Comment by gythialy** [comment]
[qlc-ptm](https://github.com/qlcchain/qlc-ptm)
