### ISSUE TITLE
optimize ledger to increase tps

### ISSUE THREAD

**Issue by zengchen221** [qlcchain/go-qlc#781]
- memory cache #773
   - [x] implement cache and sqlite index interface #798
   - [x] cache management, write-cache switch/read-cache update
   - [ ] dump to badger and sqlite
   - [ ] refactor ledger generic to support cache
- badger
   - [x] move store interface to common folder
- relation db #671
   - [ ] table schema interface of each struct
   - [ ] implement table query
   - [ ] migrate sqlite service into ledger service #783
   - [ ] support pq/mysql etc.
- log file
   - [ ] node exception exit handling
- ledger
  - [x] refactor ledger interface
  - [ ] refactor block check/process/rollback
  - [ ] synchronize block / unconfirmed block 
  - [ ] refactor ledger migration
  - [ ] ledger dump #811
  - [ ] testcase
